[controller]
controller ansible_host=CONTROLLER_PUBLIC_IP

[manager]
manager ansible_host=MANAGER_PUBLIC_IP

[workers]
worker_a ansible_host=WORKER_A_PUBLIC_IP
worker_b ansible_host=WORKER_B_PUBLIC_IP
